# Generated by Django 5.2.16 on 2026-07-28 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0005_auditoria_da_matriz_de_acesso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parecer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor_sismed_id', models.IntegerField(db_index=True)),
                ('protocolo_sismed_id', models.IntegerField(blank=True, null=True)),
                ('texto', models.TextField()),
                ('conclusao', models.CharField(choices=[('apto', 'Apto para o trabalho'), ('afastamento', 'Necessita afastamento'), ('encaminhamento', 'Necessita encaminhamento'), ('acompanhamento', 'Manter em acompanhamento')], max_length=20)),
                ('estado', models.CharField(choices=[('rascunho', 'Rascunho'), ('concluido', 'Concluído')], default='rascunho', max_length=12)),
                ('prioritario', models.BooleanField(default=False)),
                ('data_reavaliacao', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pareceres', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pareceres', to='contas.unidade')),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='EventoParecer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criado', 'Parecer criado'), ('atualizado', 'Parecer atualizado'), ('concluido', 'Parecer concluído')], max_length=12)),
                ('estado_anterior', models.CharField(blank=True, max_length=12)),
                ('estado_novo', models.CharField(max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parecer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='pareceres.parecer')),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
    ]
