# Generated by Django 5.2.16 on 2026-07-31 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0006_perfis_multidisciplinares'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor_sismed_id', models.IntegerField(db_index=True)),
                ('protocolo_sismed_id', models.IntegerField(blank=True, null=True)),
                ('especialidade', models.CharField(choices=[('neuropsicologia', 'Neuropsicólogo'), ('assistencia_social', 'Assistente Social'), ('seguranca_trabalho', 'Segurança do Trabalho')], max_length=20)),
                ('texto_solicitacao', models.TextField()),
                ('estado', models.CharField(choices=[('aberta', 'Aguardando resposta'), ('respondida', 'Respondida')], default='aberta', max_length=12)),
                ('texto_resposta', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('respondente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_apoio_respondidas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_apoio_feitas', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_apoio', to='contas.unidade')),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='EventoSolicitacaoApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criada', 'Solicitação criada'), ('respondida', 'Solicitação respondida')], max_length=12)),
                ('estado_anterior', models.CharField(blank=True, max_length=12)),
                ('estado_novo', models.CharField(max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='apoio.solicitacaoapoio')),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
    ]
